name: ML CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    # --- ĐẶT DVC Ở ĐÂY ---
    - name: Install DVC
      run: |
        pip install "dvc[http]"

    - name: Pull data from DVC
      env:
        DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      run: |
        dvc remote modify origin --local auth basic
        dvc remote modify origin --local user $DAGSHUB_USERNAME
        dvc remote modify origin --local password $DAGSHUB_TOKEN
        dvc pull
    # ----------------------

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run pipeline
      run: python automl_pipeline.py

    - name: Build Docker
      run: docker build -t automl .

    - name: Test Docker
      run: docker run automl

    - name: Test Model
      run: python test_model.py
    
    - name: Login Docker
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker Image
      run: |
        docker tag automl yuj1n/automl
        docker push yuj1n/automl